import { briefSchema, type CreativeBrief, type SourceAsset } from "./schemas";

export const OTR_PORTFOLIO_ASSETS: SourceAsset[] = [
  { id: "00000000-0000-4000-9000-000000000001", label: "OTR Services logo", kind: "logo", storagePath: "bundled/otr-services-logo.svg", mimeType: "image/svg+xml" },
  { id: "00000000-0000-4000-9000-000000000002", label: "Pressed In Pink", kind: "image", storagePath: "bundled/pressed-in-pink.svg", mimeType: "image/svg+xml" },
  { id: "00000000-0000-4000-9000-000000000003", label: "Pacific Stay Properties", kind: "image", storagePath: "bundled/pacific-stay-properties.svg", mimeType: "image/svg+xml" },
  { id: "00000000-0000-4000-9000-000000000004", label: "JMB 2 Creations", kind: "image", storagePath: "bundled/jmb2-creations.svg", mimeType: "image/svg+xml" },
  { id: "00000000-0000-4000-9000-000000000005", label: "Muerto De Hambre", kind: "image", storagePath: "bundled/mdh-grill.svg", mimeType: "image/svg+xml" },
];

export const OTR_PORTFOLIO_SITES = [
  { name: "Pressed In Pink", url: "https://pressedinpink.com", note: "E-commerce + custom orders" },
  { name: "Pacific Stay Properties", url: "https://pacificstayproperties.com", note: "Short-term rentals + direct booking" },
  { name: "JMB 2 Creations", url: "https://jmb2creations.com", note: "Custom storefront + request flow" },
  { name: "Muerto De Hambre Grill", url: "https://mdhgrill.com", note: "Restaurant + locations + catering" },
] as const;

export function otrServicesPortfolioBrief(): CreativeBrief {
  return briefSchema.parse({
    template: "Website Showcase",
    platform: "Instagram",
    aspectRatio: "9:16",
    durationSeconds: 30,
    hook: "Four businesses. Four different identities.",
    bodyCopy: "OTR Services builds websites that are designed around the business behind them.",
    cta: "Let's build yours.",
    sourceAssets: OTR_PORTFOLIO_ASSETS,
    motion: {
      pacing: "Fast",
      transitionStyle: "Punchy",
      visualStyle: "Bold",
      motionIntensity: "High",
    },
    scenes: [
      {
        type: "hook",
        durationSeconds: 3,
        text: "Your business deserves a site that feels like yours.",
        subtext: "Websites built to represent the brand behind them.",
        logoEnabled: true,
        textPosition: "center",
        textAlign: "center",
        overlayOpacity: 0.18,
        animationPreset: "pop-in",
        transitionIn: "zoom",
        transitionOut: "fade-through",
        emphasis: "strong",
        captionEnabled: false,
      },
      {
        type: "gallery",
        durationSeconds: 4,
        text: "Pressed In Pink",
        subtext: "E-commerce + custom orders • pressedinpink.com",
        backgroundAssetId: OTR_PORTFOLIO_ASSETS[1].id,
        textPosition: "bottom",
        textAlign: "left",
        overlayOpacity: 0.12,
        animationPreset: "zoom-in",
        transitionIn: "slide",
        transitionOut: "crossfade",
        emphasis: "standard",
        captionEnabled: false,
      },
      {
        type: "gallery",
        durationSeconds: 4,
        text: "Pacific Stay Properties",
        subtext: "Short-term rentals + direct booking • pacificstayproperties.com",
        backgroundAssetId: OTR_PORTFOLIO_ASSETS[2].id,
        textPosition: "bottom",
        textAlign: "left",
        overlayOpacity: 0.12,
        animationPreset: "subtle-pan",
        transitionIn: "blur-fade",
        transitionOut: "crossfade",
        emphasis: "standard",
        captionEnabled: false,
      },
      {
        type: "gallery",
        durationSeconds: 4,
        text: "JMB 2 Creations",
        subtext: "Custom storefront + request flow • jmb2creations.com",
        backgroundAssetId: OTR_PORTFOLIO_ASSETS[3].id,
        textPosition: "bottom",
        textAlign: "left",
        overlayOpacity: 0.12,
        animationPreset: "zoom-out",
        transitionIn: "slide",
        transitionOut: "crossfade",
        emphasis: "standard",
        captionEnabled: false,
      },
      {
        type: "gallery",
        durationSeconds: 4,
        text: "Muerto De Hambre Grill",
        subtext: "Restaurant + locations + catering • mdhgrill.com",
        backgroundAssetId: OTR_PORTFOLIO_ASSETS[4].id,
        textPosition: "bottom",
        textAlign: "left",
        overlayOpacity: 0.12,
        animationPreset: "zoom-in",
        transitionIn: "blur-fade",
        transitionOut: "fade-through",
        emphasis: "standard",
        captionEnabled: false,
      },
      {
        type: "service",
        durationSeconds: 4,
        text: "Different industries. One standard.",
        subtext: "Website building • website management • design + branding",
        textPosition: "center",
        textAlign: "center",
        overlayOpacity: 0.2,
        animationPreset: "reveal",
        transitionIn: "zoom",
        transitionOut: "fade-through",
        emphasis: "strong",
        captionEnabled: false,
      },
      {
        type: "end-card",
        durationSeconds: 7,
        text: "BUILT TO REPRESENT YOUR BUSINESS RIGHT.",
        subtext: "Custom websites • management • branding",
        cta: "Let's build yours • @otrservicesie",
        logoEnabled: true,
        textPosition: "center",
        textAlign: "center",
        overlayOpacity: 0.12,
        animationPreset: "end-card-focus",
        transitionIn: "fade-through",
        transitionOut: "cut",
        emphasis: "strong",
        captionEnabled: false,
      },
    ],
  });
}
